'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Common
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BSP.Common", GetType(Common).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend Shared ReadOnly Property btnAdd() As String
            Get
                Return ResourceManager.GetString("btnAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Images/Report EN.png.
        '''</summary>
        Friend Shared ReadOnly Property btnReport() As String
            Get
                Return ResourceManager.GetString("btnReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset.
        '''</summary>
        Friend Shared ReadOnly Property btnReset() As String
            Get
                Return ResourceManager.GetString("btnReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property btnSave() As String
            Get
                Return ResourceManager.GetString("btnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save All.
        '''</summary>
        Friend Shared ReadOnly Property btnSaveAll() As String
            Get
                Return ResourceManager.GetString("btnSaveAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Friend Shared ReadOnly Property btnSearch() As String
            Get
                Return ResourceManager.GetString("btnSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update.
        '''</summary>
        Friend Shared ReadOnly Property btnUpdate() As String
            Get
                Return ResourceManager.GetString("btnUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estate:.
        '''</summary>
        Friend Shared ReadOnly Property ddlEstate() As String
            Get
                Return ResourceManager.GetString("ddlEstate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language:.
        '''</summary>
        Friend Shared ReadOnly Property ddlLanguage() As String
            Get
                Return ResourceManager.GetString("ddlLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend Shared ReadOnly Property gvheaderDelete() As String
            Get
                Return ResourceManager.GetString("gvheaderDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend Shared ReadOnly Property gvheaderEdit() As String
            Get
                Return ResourceManager.GetString("gvheaderEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select.
        '''</summary>
        Friend Shared ReadOnly Property gvheaderSelect() As String
            Get
                Return ResourceManager.GetString("gvheaderSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Account Code.
        '''</summary>
        Friend Shared ReadOnly Property IAccountCode() As String
            Get
                Return ResourceManager.GetString("IAccountCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Attendance Code.
        '''</summary>
        Friend Shared ReadOnly Property IAttendanceCode() As String
            Get
                Return ResourceManager.GetString("IAttendanceCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Charge Code.
        '''</summary>
        Friend Shared ReadOnly Property IChargeCode() As String
            Get
                Return ResourceManager.GetString("IChargeCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Div Code.
        '''</summary>
        Friend Shared ReadOnly Property IDiv() As String
            Get
                Return ResourceManager.GetString("IDiv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Material Code.
        '''</summary>
        Friend Shared ReadOnly Property IMaterial() As String
            Get
                Return ResourceManager.GetString("IMaterial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Operated By.
        '''</summary>
        Friend Shared ReadOnly Property IOperatedBy() As String
            Get
                Return ResourceManager.GetString("IOperatedBy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Sub Block Code.
        '''</summary>
        Friend Shared ReadOnly Property ISubBlock() As String
            Get
                Return ResourceManager.GetString("ISubBlock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid T0 Code.
        '''</summary>
        Friend Shared ReadOnly Property IT0() As String
            Get
                Return ResourceManager.GetString("IT0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid T0 Code \nInvalid T1 Code \n Invalid T2 Code \n Invalid T3 Code \n Invalid T4 Code.
        '''</summary>
        Friend Shared ReadOnly Property IT0IT1IT2IT3IT4() As String
            Get
                Return ResourceManager.GetString("IT0IT1IT2IT3IT4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid T1 Code.
        '''</summary>
        Friend Shared ReadOnly Property IT1() As String
            Get
                Return ResourceManager.GetString("IT1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid T2 Code.
        '''</summary>
        Friend Shared ReadOnly Property IT2() As String
            Get
                Return ResourceManager.GetString("IT2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid T3 Code.
        '''</summary>
        Friend Shared ReadOnly Property IT3() As String
            Get
                Return ResourceManager.GetString("IT3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid T4 Code.
        '''</summary>
        Friend Shared ReadOnly Property IT4() As String
            Get
                Return ResourceManager.GetString("IT4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Category.
        '''</summary>
        Friend Shared ReadOnly Property IVehicleCategory() As String
            Get
                Return ResourceManager.GetString("IVehicleCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid YOP Code.
        '''</summary>
        Friend Shared ReadOnly Property IYOP() As String
            Get
                Return ResourceManager.GetString("IYOP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date :.
        '''</summary>
        Friend Shared ReadOnly Property lblDate() As String
            Get
                Return ResourceManager.GetString("lblDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are about to delete the selected record. Are you sure? If yes please click OK or click Cancel.
        '''</summary>
        Friend Shared ReadOnly Property lblDeletePrompt() As String
            Get
                Return ResourceManager.GetString("lblDeletePrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are currently no records for this screen in your database..
        '''</summary>
        Friend Shared ReadOnly Property lblEmptyRecord() As String
            Get
                Return ResourceManager.GetString("lblEmptyRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page :.
        '''</summary>
        Friend Shared ReadOnly Property lblPage() As String
            Get
                Return ResourceManager.GetString("lblPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This site is best viewed in 1280x720 resolution and Internet Explorer 7 and above..
        '''</summary>
        Friend Shared ReadOnly Property lblResolution() As String
            Get
                Return ResourceManager.GetString("lblResolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Friend Shared ReadOnly Property lgnSearch() As String
            Get
                Return ResourceManager.GetString("lgnSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search Results.
        '''</summary>
        Friend Shared ReadOnly Property lgnSearchResults() As String
            Get
                Return ResourceManager.GetString("lgnSearchResults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to We are unable to process your request at this time, Please make sure to enter all the mandatory fields and try again. If the problem still exists contact administrator..
        '''</summary>
        Friend Shared ReadOnly Property Msg0() As String
            Get
                Return ResourceManager.GetString("Msg0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data successfully saved.
        '''</summary>
        Friend Shared ReadOnly Property Msg1() As String
            Get
                Return ResourceManager.GetString("Msg1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record already exists.
        '''</summary>
        Friend Shared ReadOnly Property Msg10() As String
            Get
                Return ResourceManager.GetString("Msg10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current data conflicts with existing data in the database.Please modify start kms and/or end kms..
        '''</summary>
        Friend Shared ReadOnly Property Msg11() As String
            Get
                Return ResourceManager.GetString("Msg11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current data conflicts with existing data in the database.Please modify start time and/or end time..
        '''</summary>
        Friend Shared ReadOnly Property Msg12() As String
            Get
                Return ResourceManager.GetString("Msg12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current data conflicts with existing data in the database.Please modify FFB Delivery Order No..
        '''</summary>
        Friend Shared ReadOnly Property Msg13() As String
            Get
                Return ResourceManager.GetString("Msg13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data successfully updated.
        '''</summary>
        Friend Shared ReadOnly Property Msg2() As String
            Get
                Return ResourceManager.GetString("Msg2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data successfully deleted.
        '''</summary>
        Friend Shared ReadOnly Property Msg3() As String
            Get
                Return ResourceManager.GetString("Msg3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record already in use.
        '''</summary>
        Friend Shared ReadOnly Property Msg4() As String
            Get
                Return ResourceManager.GetString("Msg4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are attempting to modify a record that is being used elsewhere.
        '''</summary>
        Friend Shared ReadOnly Property Msg5() As String
            Get
                Return ResourceManager.GetString("Msg5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This record was posted successfully..
        '''</summary>
        Friend Shared ReadOnly Property Msg6() As String
            Get
                Return ResourceManager.GetString("Msg6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All records were posted successfully..
        '''</summary>
        Friend Shared ReadOnly Property Msg7() As String
            Get
                Return ResourceManager.GetString("Msg7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No records found matching your search criteria.
        '''</summary>
        Friend Shared ReadOnly Property MsgNoRecords() As String
            Get
                Return ResourceManager.GetString("MsgNoRecords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter the search criteria.
        '''</summary>
        Friend Shared ReadOnly Property MsgSearch() As String
            Get
                Return ResourceManager.GetString("MsgSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page Size : .
        '''</summary>
        Friend Shared ReadOnly Property PageSize() As String
            Get
                Return ResourceManager.GetString("PageSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password:.
        '''</summary>
        Friend Shared ReadOnly Property Password() As String
            Get
                Return ResourceManager.GetString("Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Basic Pay Required.
        '''</summary>
        Friend Shared ReadOnly Property RBasicPay() As String
            Get
                Return ResourceManager.GetString("RBasicPay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select public holiday as description.
        '''</summary>
        Friend Shared ReadOnly Property RPublicHolidayDescp() As String
            Get
                Return ResourceManager.GetString("RPublicHolidayDescp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time Basic Required.
        '''</summary>
        Friend Shared ReadOnly Property RTimeBasic() As String
            Get
                Return ResourceManager.GetString("RTimeBasic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select a vehicle or workshop.
        '''</summary>
        Friend Shared ReadOnly Property RVehicleWorkshop() As String
            Get
                Return ResourceManager.GetString("RVehicleWorkshop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please click the Save All/Update All button to store the data permanently in your database..
        '''</summary>
        Friend Shared ReadOnly Property SaveAllUpdateAll() As String
            Get
                Return ResourceManager.GetString("SaveAllUpdateAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User Name:.
        '''</summary>
        Friend Shared ReadOnly Property UserName() As String
            Get
                Return ResourceManager.GetString("UserName", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
