Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Gaji Pokok',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A01'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Pungut Brondolan',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A10'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Upah Kerja Borongan',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A11'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Kayu Api',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A12'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Surut Gaji',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A13'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Kontribusi Perawatan Rumah',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A14'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Dasar Latex',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A15'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Dasar Lump',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A16'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Tree Lace',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A17'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Bonus Latex',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A18'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Bonus Lump',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A19'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Lembur',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A02'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Progresif Latex',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A20'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Progresif Lump',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A21'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Cuci Mangkok',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A22'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Dotting',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A23'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Guide Lines',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A24'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Sabtu',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A25'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Ad Collection',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A26'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Dasar lembur 100 %',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A27'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Rajin',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A28'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Lain-Lain',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A29'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Tunjangan JAMSOSTEK - JHT',PPH='N',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A03'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Lembur Minggu',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A30'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Minggu',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A31'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Jasa 25/30/35 Thn',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A32'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Pembayaran Lainnya',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A33'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Asuransi Jiwa',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A34'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Kurang Bayar/Lain-Lain',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A35'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Transport',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A36'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Tunjangan JAMSOSTEK - JKK',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A37'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Tunjangan JAMSOSTEK - JK',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A38'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Bonus',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A39'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Tunjangan Pajak',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A04'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'THR',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A40'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Surut Lembur',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A41'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Bantuan Anak Sekolah',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A42'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Potongan Jamsostek (BPJS)',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D01'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Jamsostek Beban PKJ',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D02'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Pembulatan Bulan Lalu',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D03'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Pot. Meras Mangkir',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D04'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Pot. Tunjangan Beras',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D05'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Pot. Tengahan Bulan I',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D06'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Pot. Tengahan Bulan II',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D07'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Tunjangan Beras',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A05'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'PPH Psl 21',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D08'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Iuran SPSI',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D09'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Iuran SBSI',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D10'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'STM SPSI',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D11'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'STM SBSI',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D12'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Pinjaman Uang',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D13'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Sisa Biaya Dinas',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D14'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Pot. Alat-Alat Kerja',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D15'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Biaya Pengobatan/RS',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D16'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Hutang Kacamata',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D17'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Kontribusi Perumahan',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A06'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Hutang Telepon',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D18'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Hutang Listrik/PLN',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D19'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Hutang Uang Koperasi',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D20'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Hutang Lain-lain',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D21'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Hutang Listrik Koperasi',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D22'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Hutang Barang Koperasi',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D23'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Denda Pajak/Pajak Sp.Motor',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D24'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Hutang Bank Koperasi',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D25'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Sukarela Koperasi',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D26'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Iuran Koperasi',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D27'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'BPJS KES. PERUSAHAAN',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A07'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Jasa 25/30/35 Thn',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D28'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Kontr. Perawatan Rumah',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D29'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'POT. BPJS KES. PERSHN',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D30'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'POT. BPJS KES.  BEBAN KRY',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D31'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Lebih Bayar/lain-2',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D32'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Uang Muka Deres Minggu',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D33'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Pot. JAMSOSTEK - JKK',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D34'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Pot. JAMSOSTEK - JK',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D35'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Pot. Asuransi Jiwa',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D36'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Bonus',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D37'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Panen Sawit',PPH='Y',NoTransferToSalary=1,FixedAllowance = 0 WHERE AllowDedCode = 'A08'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'THR',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D38'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Bantuan Anak Sekolah',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'D39'
Update Checkroll.AllowanceDeductionSetup Set Remarks = 'Premi Langsir Buah',PPH='Y',NoTransferToSalary=0,FixedAllowance = 0 WHERE AllowDedCode = 'A09'
